-- generated by sigil-settings (Input page); loaded from hyprland.lua with pcall(dofile). Safe to delete.
hl.config({ input = {
    repeat_rate = 25, repeat_delay = 600,
    sensitivity = -0.15,
    touchpad = {
        natural_scroll = true, tap_to_click = true,
        disable_while_typing = true, clickfinger_behavior = true,
        scroll_factor = 1.00,
    },
} })
