-- generated by sigil-settings (Tablet page); loaded from hyprland.lua with pcall(dofile). Safe to delete.
-- Wacom Intuos BT S - 152.0 x 95.0 mm surface, 4096 pressure levels
hl.config({ input = {
    tablet = {
        output = "eDP-1",
        left_handed = true,
        relative_input = false,
        -- proportions forced to eDP-1 (1.78:1)
        active_area_size     = { 152.0, 85.5 },
        active_area_position = { 0.0, 4.8 },
    },
} })
